apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml

images:
  - name: roslinmahmud/log-generator
    newTag: latest # The CI will overwrite "latest" with the real SHA
  - name: roslinmahmud/log-response
    newTag: latest