apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml

images:
- name: roslinmahmud/log-generator
  newName: roslinmahmud/log-generator
  newTag: e0127581fdf72e4bce2143211eab30c9a1308c0b
- name: roslinmahmud/log-response
  newName: roslinmahmud/log-response
  newTag: e0127581fdf72e4bce2143211eab30c9a1308c0b
