apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml

images:
- name: roslinmahmud/log-generator
  newName: roslinmahmud/log-generator
  newTag: fd4e104695095c2949ea25511ffc8050d482a9f7
- name: roslinmahmud/log-response
  newName: roslinmahmud/log-response
  newTag: fd4e104695095c2949ea25511ffc8050d482a9f7
