apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 8000
