apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/statefulset.yaml
  - manifests/gateway.yaml
  - manifests/route.yaml


images:
  - name: roslinmahmud/ping-pong
    newTag: latest