apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: roslinmahmud/todo-app:latest
          env:
            - name: PORT
              value: "8000"
            - name: IMAGE_URL
              value: "https://picsum.photos/1200"
            - name: CACHE_DURATION
              value: "600"
            - name: IMAGE_FILE
              value: "files/cached_image.jpg"
            - name: METADATA_FILE
              value: "files/cache_metadata.json"
            - name: STATIC_DIR
              value: "files"
            - name: FRONTEND_DIR
              value: "frontend"
            - name: HOST
              value: "0.0.0.0"
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_NAME
              value: "tododb"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"
          volumeMounts:
            - name: files-volume
              mountPath: /app/files
      volumes:
        - name: files-volume
          persistentVolumeClaim:
            claimName: todo-pvc