apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- manifests/pv/PersistentVolumeClaim.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/ingress.yaml
- manifests/postgres-statefulset.yaml
- manifests/cronjob.yaml
- manifests/backup-cronjob.yaml
- manifests/hpa.yaml

images:
- name: roslinmahmud/todo-app
  newName: roslinmahmud/todo-app
  newTag: 97e14ffeb9cbdc128ab81a4499927bd36900fafd
