apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
spec:
  storageClassName: todo-pv  # Must match the PV's storageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Must match or be less than PV capacity