apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-pv
spec:
  storageClassName: todo-pv  # Storage class name for claiming this volume
  capacity:
    storage: 1Gi  # Size of the volume
  volumeMode: Filesystem  # Mounted as a directory
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube  # Local path on the node (ensure this directory exists)
  nodeAffinity:  # Required for local volumes
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0  # Node where the volume is available