apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project
  annotations:
    cloud.google.com/backend-config: '{"default": "todo-backend-config"}'
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8000
