name: Build and publish todo-app

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'todo-app/**'
      - '.github/workflows/main.yaml'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=$GITHUB_SHA" >> $GITHUB_OUTPUT
            echo "ENVIRONMENT=staging" >> $GITHUB_OUTPUT
          fi

      - name: Build and publish todo-app
        working-directory: ./todo-app
        run: |-
          docker build --tag "roslinmahmud/todo-app:${{ steps.vars.outputs.IMAGE_TAG }}" .
          docker push "roslinmahmud/todo-app:${{ steps.vars.outputs.IMAGE_TAG }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update staging overlay
        if: steps.vars.outputs.ENVIRONMENT == 'staging'
        working-directory: ./todo-app/manifests/overlays/staging
        run: |-
          kustomize edit set image roslinmahmud/todo-app=roslinmahmud/todo-app:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Update production overlay
        if: steps.vars.outputs.ENVIRONMENT == 'production'
        working-directory: ./todo-app/manifests/overlays/production
        run: |-
          kustomize edit set image roslinmahmud/todo-app=roslinmahmud/todo-app:${{ steps.vars.outputs.IMAGE_TAG }}

      - name: Commit kustomization changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'todo-app/manifests/overlays/*/kustomization.yaml'
          message: "Update ${{ steps.vars.outputs.ENVIRONMENT }} to version ${{ steps.vars.outputs.IMAGE_TAG }}"