name: Build and publish todo-app

on:
  push:
    paths:
      - 'todo-app/**'
      - '.github/workflows/main.yaml'

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and publish todo-app
      - name: Build and publish todo-app
        working-directory: ./todo-app
        run: |-
          docker build --tag "roslinmahmud/todo-app:$GITHUB_SHA" .
          docker push "roslinmahmud/todo-app:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        working-directory: ./todo-app
        run: |-
          kustomize edit set image roslinmahmud/todo-app=roslinmahmud/todo-app:$GITHUB_SHA

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'todo-app/kustomization.yaml'
          message: New version released ${{ github.sha }}